### ISSUE TITLE
It is support NSURLUploadTask?  

### ISSUE THREAD

**Issue by BhaveshKumbhani** [FabrizioBrancati/Queuer#13]
Is it work in NSURLUploadTask in background/suspended state of app. 

I want to upload task execute in synchronize manner.  

Let's say 10 task in queue. 
It should execute in queue one by one like... 1, 2,3..etc

Need to upload thousands of images in background. 

Please advise and suggestions are greatly appreciated.

**Comment by FabrizioBrancati** [comment]
Sorry for late reply, you just have to create your `UploadTask` as a subclass of `ConcurrentOperation`.
Override the `execute()` function and call `finish()` inside it.
You can find all you need inside this [class file](https://github.com/FabrizioBrancati/Queuer/blob/master/Sources/Queuer/ConcurrentOperation.swift)

**Comment by FabrizioBrancati** [comment]
Hi @BhaveshKumbhani, news on that? 😄

**Comment by BhaveshKumbhani** [comment]
Background task managed by OS, while in background,  So we can't deside to priority for execution.

I have successful integrate multiple task run in background without any operation queue, Around thousands of task are tested and working fine. 

Few limitations in hardware,  thats why background task manage by os it self. 

- weak network
- low battery
- task overload
