### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by marinofaggiana** [FabrizioBrancati/Queuer#18]
Hi @FabrizioBrancati , very a good job !! but examples would be appreciated for the Asynchronous Operation

Cheers
m.

**Comment by FabrizioBrancati** [comment]
Hi @marinofaggiana, thanks 😄 
What kind of examples do you need?

If you are looking for a `ConcurrentOperation` subclass, you can take a look at the [SynchronousOperation](https://github.com/FabrizioBrancati/Queuer/blob/master/Sources/Queuer/SynchronousOperation.swift) subclass implementation.

Let me know if you need anything else!

**Comment by marinofaggiana** [comment]
Hi @FabrizioBrancati, tanks for your response, with semaphore? I need of a maxConcurrentOperationCount = 5 but I don't understand your implementation... can you explain a small example for this ?

**Comment by FabrizioBrancati** [comment]
You can find an example on the [README](https://github.com/FabrizioBrancati/Queuer#semaphore) or inside the [SemaphoreTests.swift](https://github.com/FabrizioBrancati/Queuer/blob/master/Tests/QueuerTests/SemaphoreTests.swift) file in the `Tests` folder.

If it's not enough, what's your use case?

**Comment by marinofaggiana** [comment]
Thanks @FabrizioBrancati I need e.g. of read 1000 files with a async func e.g.

func download (filename: string, completion: @escaping (_ errorCode: Int) -> ()) 

but with max 5 download in execution, we already have a class for this but I am interested to try with you lib if can streamline the code :-)

**Comment by FabrizioBrancati** [comment]
Why do you need a semaphore?

You can just create 1000 `ConcurrentOperation`s and adding them to a queue by setting `maxConcurrentOperationCount` property to `5`.
They will be executed by 5 until they end.
If you want, you can subclass `ConcurrentOperation` to create your custom operation to be added to the queue.

**Comment by marinofaggiana** [comment]
yes, of better NO, we have look you code and now is clear. thanks

**Comment by FabrizioBrancati** [comment]
Are you sure?
Can I close the issue? 😄

**Comment by marinofaggiana** [comment]
Can be improved?

```
import Foundation
import Queuer

@objc class NCOperationQueue: NSObject {
    @objc public static let shared: NCOperationQueue = {
        let instance = NCOperationQueue()
        return instance
    }()
    
    let downloadQueue = Queuer(name: "downloadQueue", maxConcurrentOperationCount: 5, qualityOfService: .default)
    
    @objc func download(fileName: String) {
        downloadQueue.addOperation(NCOperationDownload.init(filename: filename))
    }
}

class NCOperationDownload: ConcurrentOperation {
   
    private var filename: String
    
    init(filename: String) {
        self.filename = filename
    }
    
    override func start() {
        NCNetworking.shared.download(filename: self.filename) { (_) in
            self.finish()
        }
    }
}

```

**Comment by FabrizioBrancati** [comment]
You can take a look at the [RequestOperation](https://github.com/FabrizioBrancati/Queuer/blob/1.3.2/Sources/Queuer/RequestOperation.swift) that was implemented in the first version of Queuer.

There are a lot of ways to improve your code 😉

**Comment by FabrizioBrancati** [comment]
Did you take a look at the [RequestOperation](https://github.com/FabrizioBrancati/Queuer/blob/1.3.2/Sources/Queuer/RequestOperation.swift) source file?

**Comment by FabrizioBrancati** [comment]
Hi @marinofaggiana news about this? 😄

**Comment by marinofaggiana** [comment]
Hi @FabrizioBrancati sorry for the long time, all ok, we can close this.
