### ISSUE TITLE
Unable to subclass due to Public Access Control restrictions 

### ISSUE THREAD

**Issue by rchapmanRP** [FabrizioBrancati/Queuer#2]
Installed with CococaPods and running Xcode 8.3 / Swift 3.1.

Subclassing `ConcurrentOperation` in my own project with `import Queuer` as per the README.

On compile, getting the error: 
> Cannot inherit from non-open class `ConcurrentOperation` outside of its defining module.

and
> Overriding non-open instance method outside of its defining module.

First error fixed by changing `ConcurrentOperation` from `public` to `open`.  Must also change the overrides in the class to `open` to match Access Controls of `Operation`.

Second error fixed by making `-ConcurrentOperation.execute()` open as well.

**Comment by FabrizioBrancati** [comment]
You are right! My fault, I was using this project by importing its files and not as a framework.
Thanks for all the info, I will fix this 👍

**Comment by FabrizioBrancati** [comment]
You can use the `master` branch until I release a new version 👍

**Comment by rchapmanRP** [comment]
Awesome! Re-installed from master and its working.

**Comment by FabrizioBrancati** [comment]
I have just released a new version (`1.1.0`) that includes this fix, point to that instead of `master` if you want!
