### ISSUE TITLE
finish(success: Bool) does nothing to success

### ISSUE THREAD

**Issue by mradzinski** [FabrizioBrancati/Queuer#21]
Finishing a `ConcurrentOperation` with `operation.finish(success: false)` does nothing to its `success` property. I would expect `success` to be false if I finish the operation that way 🤔

**Comment by FabrizioBrancati** [comment]
I created a PR to fix this (#22).
Thanks for spotting this!

**Comment by FabrizioBrancati** [comment]
This fix is now on `develop` 😉
