### ISSUE TITLE
Chained operation results

### ISSUE THREAD

**Issue by LebonNic** [FabrizioBrancati/Queuer#23]
Hello,

I am discovering this project which looks super interesting. However, I have a question about the `Queuer` class and the `addChainedOperations` method. Is it possible for the queued operations to pass the result of their process to the next one?

For example:
Operation1 -> Copies a file in a temporary directory and returns an URL.
Operation2 -> Takes an URL as input and uploads the corresponding file on a server.

Is it possible for Operation2 to get the input from Operation1 if they are queued with `addChainedOperations`?

Best regards,
Nicolas

**Comment by FabrizioBrancati** [comment]
Hi @LebonNic, currently it's not supported, but is something that I would like to implement, I also wrote it in the [README.md file](https://github.com/FabrizioBrancati/Queuer#features) 😄 
> Data layer that every operation inside an OperationQueue can access

**Comment by LebonNic** [comment]
Oh yes! Sorry I missed that line in the README... Thank you for responding so quickly!
