### ISSUE TITLE
SPM Warning

### ISSUE THREAD

**Issue by marinofaggiana** [FabrizioBrancati/Queuer#24]
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.

**Comment by FabrizioBrancati** [comment]
Maybe I should raise the compatibility version to iOS 9.
Thanks for the issue, I will let you know once done or I have more informations 👍

**Comment by FabrizioBrancati** [comment]
This is now fixed on Queuer 3.0.0 🎉
