### ISSUE TITLE
Serial task

### ISSUE THREAD

**Issue by dajiangjun887** [FabrizioBrancati/Queuer#25]
The call of interface A returns the result and interface B is called, interface B finishes calling C, and finally synthesizes and renders. This kind of blocking doesn't seem to work.

**Comment by FabrizioBrancati** [comment]
Hi @dajiangjun887, can you please give me more details about your issue?
There is a test that simulates that exactly thing: https://github.com/FabrizioBrancati/Queuer/blob/master/Tests/QueuerTests/QueuerTests.swift#L156

**Comment by dajiangjun887** [comment]
sorry, Maybe I didn’t understand how to use it before. I used pause-open to enable it to be executed in serial blocking order. I hope to produce a Demo to demonstrate all operations.

**Comment by FabrizioBrancati** [comment]
Hi @dajiangjun887 news about this issue? 😄
