### ISSUE TITLE
Documentation link seems broken

### ISSUE THREAD

**Issue by cristianilea-lateral** [FabrizioBrancati/Queuer#26]
https://github.fabriziobrancati.com/documentation/Queuer/

**Comment by FabrizioBrancati** [comment]
Thanks! I need to redeploy it on a different server! 😄

**Comment by cristianilea-lateral** [comment]
Can you please fix this? It's been over 2 months

**Comment by FabrizioBrancati** [comment]
@cristianilea-lateral you can find the new Xcode 13.0 beta generated documentation [here](https://github.com/FabrizioBrancati/Queuer/tree/develop/Resources/Queuer.doccarchive).

Added in this [commit](https://github.com/FabrizioBrancati/Queuer/commit/f1e431d7d9c262a5f55f64f5b34f1fe15f0d68ca). Let me know your thoughts

**Comment by FabrizioBrancati** [comment]
This is now fixed on Queuer 3.0.0 🎉 
The DocC plugin has been added, so you can generate it by running `swift package --disable-sandbox preview-documentation`.
It will also be available from tomorrow on [Swift Package Index](https://swiftpackageindex.com/FabrizioBrancati/Queuer)
