### ISSUE TITLE
documentation is not available

### ISSUE THREAD

**Issue by changmingw96** [FabrizioBrancati/Queuer#30]
I can't open documentation. Can you please fix the link?

**Comment by FabrizioBrancati** [comment]
@changmingw96 can you please check this issue? https://github.com/FabrizioBrancati/Queuer/issues/26
You can find the new Xcode 13.0 beta generated documentation [here](https://github.com/FabrizioBrancati/Queuer/tree/develop/Resources/Queuer.doccarchive).

**Comment by FabrizioBrancati** [comment]
This is now fixed on Queuer 3.0.0 🎉 
The DocC plugin has been added, so you can generate it by running `swift package --disable-sandbox preview-documentation`.
It will also be available from tomorrow on [Swift Package Index](https://swiftpackageindex.com/FabrizioBrancati/Queuer)
